
[font]
size = 11.0

[font.normal]
family = "RobotoMono Nerd Font"

[mouse]
hide_when_typing = true

[window]
opacity = 1.0

[window.padding]
x = 0
y = 0

[general]
import = ["/home/yoyo/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
