unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

set -as terminal-features 'alacritty:RGB,clipboard'
set -as terminal-features '*:hyperlinks'
set -s set-clipboard on

bind c new-window -c "#{pane_current_path}"
bind C-Space last-window
bind q confirm-before -p "kill-window #W? (y/n)" kill-window

unbind S-Left
unbind S-Right
unbind h
unbind j
unbind k
unbind l
bind -r H resize-pane -L 25
bind -r L resize-pane -R 25
bind -r K resize-pane -U 7
bind -r J resize-pane -D 7
bind -r C-h select-pane -L
bind -r C-l select-pane -R
bind -r C-k select-pane -U
bind -r C-j select-pane -D
bind \" split-window -h -c "#{pane_current_path}"
bind % split-window -v -c "#{pane_current_path}"

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_date_time "%d.%m.%Y %H:%M"
set -g @catppuccin_status_modules_right "application session battery date_time"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"




# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tmux-battery'

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.local/share/tmux/plugins/"
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.local/share/tmux/plugins/tpm/tpm'
